#!/bin/bash
#Note: Synclient connects to the synaptics touchpad directly, not through the X server. So we don't need "DISPLAY".
#Being root is enough to get this right.
if [ "$ACTION" == "add" ]; then 
	/usr/bin/synclient TouchpadOff=1
else
	/usr/bin/synclient TouchpadOff=0
fi
set >/tmp/usbdebug
